# Generated by Django 6.1 on 2026-09-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_documentation_projectdocumentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocumentation',
            name='image',
            field=models.ImageField(upload_to='project_documentation/'),
        ),
    ]
