# Generated by Django 6.1 on 2026-09-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_projectdocumentation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocumentation',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
