# Generated by Django 6.1 on 2026-09-15 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_projectdocumentation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='documentation',
        ),
    ]
