# Generated by Django 6.1 on 2026-09-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_project_documentation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDocumentation',
        ),
    ]
